baseURL = "https://cogitating-ceviche.com"
title = "The Cogitating Ceviche"
theme = "ananke"

[pagination]
  pagerSize = 35

[author]
  name = "Conrad T. Hannon"

[params]
  author = "Conrad T. Hannon"
  description = "Where history meets modern madness - satirical commentary by Conrad T. Hannon"
  favicon = "/images/fish-logo.png"
  site_logo = "/images/fish-logo.png"
  mainSections = ["external-articles"]
  recent_posts_number = 20
  
[params.ananke]
  show_recent_posts = true
  
[[params.ananke_socials]]
  name = "substack"
  url = "https://thecogitatingceviche.substack.com"
  
[[params.ananke_socials]]
  name = "substack"
  url = "https://thecyberneticceviche.substack.com"

[[menu.main]]
  name = "The Cogitating Ceviche"
  url = "https://thecogitatingceviche.substack.com/"
  weight = 10

[[menu.main]]
  name = "The Cybernetic Ceviche"
  url = "https://thecyberneticceviche.substack.com/"
  weight = 20

[[menu.main]]
  name = "LinkTree"
  url = "https://linktr.ee/CogitatingCeviche"
  weight = 30

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 40
