name: Update Content and Deploy

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    
    - name: Run content ingestion
      timeout-minutes: 10
      run: |
        echo "Starting content ingestion..."
        timeout 600 python3 ingest_external_articles.py
        if [ $? -eq 0 ]; then
          echo "✅ Content ingestion completed successfully."
        elif [ $? -eq 124 ]; then
          echo "⏰ Content ingestion timed out after 10 minutes"
          exit 1
        else
          echo "❌ Content ingestion failed"
          exit 1
        fi
    
    - name: Build Hugo site
      timeout-minutes: 5
      run: |
        echo "Building Hugo site..."
        hugo --gc --minify --enableGitInfo --baseURL "https://cogitating-ceviche.com" --logLevel info
        if [ $? -eq 0 ]; then
          echo "✅ Hugo build completed successfully."
          echo "Site size: $(du -sh public/)"
        else
          echo "❌ Hugo build failed"
          exit 1
        fi
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
        force_orphan: true
        cname: cogitating-ceviche.com
        enable_jekyll: false
        commit_message: ${{ github.event.head_commit.message }}
    
